### ISSUE TITLE
Is the newest version allready finished?

### ISSUE THREAD

**Issue by Goetterescu** [tritonas00/RoRServerBot#5]
The batch file which executes the program is missing, will it be added in the near future, or do I have to copy these files over the old version?

**Comment by tritonas00** [comment]
Hi! Just run what that file used to run:

https://github.com/tritonas00/RoRServerBot/blob/1bc778385fc5d70087b10a1d41cb309e551175d6/start_bot.bat

`C:\Python(Version)\python.exe -B services_start.py` will do it

**Comment by Goetterescu** [comment]
Okay, thanks. But please implement it into the folder

**Comment by Goetterescu** [comment]
Edit: Im getting this error when launching the batch file
`C:\Users\Administrator\Desktop\RoRServerBot-master>C:\Python27\python.exe -B services_start.py
  File "services_start.py", line 409
    async def on_ready(self):
            ^
SyntaxError: invalid syntax`

**Comment by tritonas00** [comment]
The bot requires python 3+, and discord.py

**Comment by Goetterescu** [comment]
Is there a tutorial on how and where to put discord.py? Cause Im really confused right now

**Comment by tritonas00** [comment]
```
# Linux/macOS
python3 -m pip install -U discord.py

# Windows
py -3 -m pip install -U discord.py
```

https://pypi.org/project/discord.py/

**Comment by Goetterescu** [comment]
Thanks
